---
abstract: 'Perl Superglue for Web frameworks and Web Servers (PSGI toolkit)'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Devel::StackTrace: 1.23
  Devel::StackTrace::AsHTML: 0.11
  File::ShareDir: 1.00
  Filesys::Notify::Simple: 0
  HTTP::Body: 1.06
  HTTP::Message: 5.814
  Hash::MultiValue: 0.05
  LWP::UserAgent: 5.814
  Pod::Usage: 1.36
  Test::TCP: 0.11
  Try::Tiny: 0
  URI: 1.36
  parent: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/miyagawa/plack/issues
  homepage: http://plackperl.org
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/Plack.git
version: 0.9985
