#!/usr/bin/perl
use strict;
use lib "lib";
use Cwd;
use Getopt::Std;
use Plack::Loader;
use Pod::Usage;

getopts('c:i:', \my %opts);
$ENV{PLACK_IMPL} ||= $opts{i};

my $file = $opts{c} || "app.psgi";
my $handler = load_handler($opts{c} || Cwd::cwd . "/app.psgi");

unless ($handler) {
    die $@ if $@;
    die "$file not found.\n";
}

my @args = map { s/^--//; $_ } @ARGV;
my $impl = Plack::Loader->auto(@args);
$impl->run($handler);
$impl->run_loop if $impl->can('run_loop'); # run event loop

sub load_handler {
    my $file = shift;
    return unless -e $file;
    return do $file;
}

__END__

=head1 NAME

plackup

=head1 SYNOPSIS

  # read your app from app.psgi file
  plackup

  # can be passed with -c option
  plackup -c hello.psgi

  # switch implementations
  env PLACK_IMPL=Mojo plackup --port 9999

  # Or, -i
  plackup -i AnyEvent

=cut
