name: linux

on:
  - push

jobs:
  perl-versions:
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v2
        with:
          since-perl: 5.14

  perl:
    needs: perl-versions
    runs-on: ubuntu-latest
    name: "Perl ${{ matrix.perl-version }}"
    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(needs.perl-versions.outputs.perl-versions) }}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: cpanm -nq --with-develop --with-recommends --with-suggests --installdeps .
      - name: Run Tests
        run: prove -lr t
        env:
          RELEASE_TESTING: 1
          AUTOMATED_TESTING: 1
